package com.pranavs.toastlibrary

enum class CustomGravity {
    GRAVITY_TOP,
    GRAVITY_BOTTOM,
    GRAVITY_CENTER,
    GRAVITY_TOP_LEFT,
    GRAVITY_BOTTOM_LEFT,
    GRAVITY_TOP_RIGHT,
    GRAVITY_BOTTOM_RIGHT,
    GRAVITY_TOP_FULL,
    GRAVITY_BOTTOM_FULL,
    GRAVITY_CENTER_FULL,
    GRAVITY_NORMAL
}
