package com.pranavs.toastlibrary

enum class CustomStyles {
    STYLE_INFO,
    STYLE_WARNING,
    STYLE_NORMAL,
    STYLE_SUCCESS,
    STYLE_ERROR,
    STYLE_MESSEGE,
    STYLE_CONFUSE,
    STYLE_INFO_CURVED,
    STYLE_WARNING_CURVED,
    STYLE_NORMAL_CURVED,
    STYLE_SUCCESS_CURVED,
    STYLE_ERROR_CURVED,
    STYLE_MESSEGE_CURVED,
    STYLE_CONFUSE_CURVED
}